### ISSUE TITLE
Cant get samples with cortex to work

### ISSUE THREAD

**Issue by myoung34** [TheHive-Project/Docker-Templates#23]
All of the samples with cortex break in different ways

* `docker-compose network create proxy` should be added to the README for these
* `docker-compose up` does not work, but is so noisy its hard to debug
* Ran `docker-compose up elasticsearch` got elasticsearch to work
* Ran `docker-compose up cortex` in another tmux tab after elasticsearch gives ```cortex           | [error] o.e.d.DBConfiguration - ElasticSearch request failure: POST:/cortex_5/_search?scroll=60000ms
cortex           | StringEntity({"seq_no_primary_term":"true","query":{"bool":{"must":[{"term":{"relations":{"value":"worker"}}},{"match_all":{}}]}},"from":0,"sort":[{"_doc":{"order":"desc"}}]},Some(application/json))
cortex           |  => ElasticError(index_not_found_exception,no such index [cortex_5],Some(_na_),Some(cortex_5),None,List(ElasticError(index_not_found_exception,no such index [cortex_5],Some(_na_),Some(cortex_5),None,null,None,None,None,List())),None,None,None,List())
cortex           | [warn] o.e.d.SearchWithScroll - Search error
cortex           | org.elastic4play.IndexNotFoundException$: null
cortex           |      at org.elastic4play.IndexNotFoundException$.<clinit>(Errors.scala)
cortex           |      at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:155)
cortex           |      at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
cortex           |      at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
cortex           |      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
cortex           |      at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
cortex           |      at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
cortex           |      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
cortex           |      at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
cortex           |      at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
^CGracefully stopping... (press Ctrl+C again to force)```

**Comment by priamai** [comment]
Try to debug to check whether Elasticsearch is working properly with the indices and templates as I did here: https://github.com/TheHive-Project/Docker-Templates/issues/35
In your case seems like Cortex didn't create the index in ES.
