### ISSUE TITLE
elasticsearch errors 

### ISSUE THREAD

**Issue by robomotic** [TheHive-Project/Docker-Templates#24]
Hello I am getting this error on all the thehive4 template variations with the elasticsearch container.
For example for thehive4-cortex31-nodered:

```
[0.000s][error][logging] Error opening log file 'logs/gc.log': Permission denied
[0.000s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:126)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)
```

The ES container is always restarting state.

**Comment by robomotic** [comment]
I also noticed that only cortex and es are up but not the other ones:

```
thehive4-cortex31-nodered$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                              NAMES
58a3b7d61718   thehiveproject/cortex:latest   "/opt/cortex/entrypo…"   5 minutes ago   Up 5 minutes   0.0.0.0:9001->9001/tcp             cortex
e1eacf9fcef8   elasticsearch:7.9.3            "/tini -- /usr/local…"   5 minutes ago   Up 1 second    0.0.0.0:9200->9200/tcp, 9300/tcp   elasticsearch
```
Lots of errors for Hive4 container in the logs.

**Comment by dadokkio** [comment]
You can read [here - Under Mapping Volumes](https://github.com/TheHive-Project/Docker-Templates/blob/main/docker/thehive4-cortex3-misp-shuffle/README.md) a lot of configuration required in order to make everything working properly.

**Comment by robomotic** [comment]
Wow there is a lot of stuff in there, I will take a look and report here. 
Cheers.

**Comment by robomotic** [comment]
Yes it was just a permission issue.

**Comment by bastianhjaeger** [comment]
@robomotic Maybe you elaborate how you solved the issue, so that other users can benefit from it.

**Comment by 0l4y4** [comment]
Hi!

```
cd Docker-Templates/docker/thehive4-cortex3-misp-shuffle
sudo chown 1000:1000 vol/elasticsearch_logs && sudo chown 1000:1000 vol/elasticsearch_data
```

FYI
