### ISSUE TITLE
Unable to start thehive4-minimal

### ISSUE THREAD

**Issue by cudeso** [TheHive-Project/Docker-Templates#27]
Starting thehive4-minimal via the docker-compose file causes the below errors. The docker daemon is working correctly as it is servicing other containers.

```
Status: Downloaded newer image for thehiveproject/thehive4:latest
Creating thehive4-minimal_thehive_1 ... done
Attaching to thehive4-minimal_thehive_1
thehive_1  | [info] ScalligraphApplication [|] Loading application ...
thehive_1  | [info] o.t.s.ScalligraphModule [|] Loading scalligraph module
thehive_1  | [info] a.e.s.Slf4jLogger [|] Slf4jLogger started
thehive_1  | [info] a.r.a.t.ArteryTcpTransport [|] Remoting started with transport [Artery tcp]; listening on address [akka://application@127.0.0.1:32869] with UID [1700451959803731164]
thehive_1  | [info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:32869] - Starting up, Akka version [2.6.10] ...
thehive_1  | [info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:32869] - Registered cluster JMX MBean [akka:type=Cluster]
thehive_1  | [info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:32869] - Started up successfully
thehive_1  | [info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:32869] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
thehive_1  | [info] a.c.s.SplitBrainResolver [|] SBR started. Config: strategy [KeepMajority], stable-after [20 seconds], down-all-when-unstable [15 seconds], selfUniqueAddress [akka://application@127.0.0.1:32869#1700451959803731164], selfDc [default].
thehive_1  | [info] o.r.Reflections [|] Reflections took 288 ms to scan 1 urls, producing 160 keys and 2415 values
thehive_1  | [info] o.t.t.ClusterSetup [|] Initialising cluster
thehive_1  | [info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:32869] - Node [akka://application@127.0.0.1:32869] is JOINING itself (with roles [dc-default], version [0.0.0]) and forming new cluster
thehive_1  | [info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:32869] - is the new leader among reachable nodes (more leaders may exist)
thehive_1  | [info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:32869] - Leader is moving node [akka://application@127.0.0.1:32869] to [Up]
thehive_1  | [info] o.t.t.ClusterListener [|] Member is Up: akka://application@127.0.0.1:32869
thehive_1  | [info] a.c.s.SplitBrainResolver [|] This node is now the leader responsible for taking SBR decisions among the reachable nodes (more leaders may exist).
thehive_1  | [info] a.c.s.ClusterSingletonManager [|] Singleton manager starting singleton actor [akka://application/system/singletonManagerJanusClusterManager/JanusClusterManager]
thehive_1  | [info] a.c.s.ClusterSingletonManager [|] ClusterSingletonManager state change [Start -> Oldest]
thehive_1  | [info] a.c.s.ClusterSingletonProxy [|] Singleton identified at [akka://application/system/singletonManagerJanusClusterManager/JanusClusterManager]
thehive_1  | Oops, cannot start the server.
thehive_1  | java.nio.file.AccessDeniedException: /opt/thp/thehive/db/je.properties
thehive_1  | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
thehive_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
thehive_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
thehive_1  | 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
thehive_1  | 	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
thehive_1  | 	at java.nio.file.Files.newOutputStream(Files.java:216)
thehive_1  | 	at org.thp.scalligraph.janus.JanusDatabase$.$anonfun$openDatabase$1(JanusDatabase.scala:49)
thehive_1  | 	at org.thp.scalligraph.janus.JanusDatabase$.$anonfun$openDatabase$1$adapted(JanusDatabase.scala:45)
thehive_1  | 	at scala.Option.foreach(Option.scala:407)
thehive_1  | 	at org.thp.scalligraph.janus.JanusDatabase$.openDatabase(JanusDatabase.scala:45)
thehive_1  | 	at org.thp.scalligraph.janus.JanusDatabaseProvider.$anonfun$get$3(JanusDatabaseProvider.scala:105)
thehive_1  | 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
thehive_1  | 	at scala.util.Success.map(Try.scala:213)
thehive_1  | 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
thehive_1  | 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
thehive_1  | 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
thehive_1  | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
thehive_1  | 	at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$2(ContextPropagatingDisptacher.scala:56)
thehive_1  | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
thehive_1  | 	at org.thp.scalligraph.DiagnosticContext$$anon$2.withContext(ContextPropagatingDisptacher.scala:75)
thehive_1  | 	at org.thp.scalligraph.ContextPropagatingDisptacher$$anon$1.$anonfun$execute$1(ContextPropagatingDisptacher.scala:56)
thehive_1  | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
thehive_1  | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
thehive_1  | 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
thehive_1  | 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
thehive_1  | 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
thehive_1  | 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by cudeso** [comment]
Changing the permissions on vol/ to **777** solved the problem.

**Comment by lnn2204** [comment]
Hmm, I got this error too. But change the permissions can't fix it

**Comment by GuillaumeBrn** [comment]
> Hmm, I got this error too. But change the permissions can't fix it

Have you tried this command:
`sudo chmod -R 777 vol/`

It should be working.
